"""Add detailed fields to Protocol model

Revision ID: b9e575a19075
Revises: c94e775b900e
Create Date: 2025-09-03 21:25:08.267503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9e575a19075'
down_revision: Union[str, Sequence[str], None] = 'c94e775b900e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocols', sa.Column('url', sa.String(), nullable=True))
    op.add_column('protocols', sa.Column('logo', sa.String(), nullable=True))
    op.add_column('protocols', sa.Column('chains', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocols', 'chains')
    op.drop_column('protocols', 'logo')
    op.drop_column('protocols', 'url')
    # ### end Alembic commands ###
