"""Create protocols table

Revision ID: c94e775b900e
Revises: 
Create Date: 2025-09-02 00:45:49.534896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94e775b900e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('tvl', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocols_id'), 'protocols', ['id'], unique=False)
    op.create_index(op.f('ix_protocols_name'), 'protocols', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_protocols_name'), table_name='protocols')
    op.drop_index(op.f('ix_protocols_id'), table_name='protocols')
    op.drop_table('protocols')
    # ### end Alembic commands ###
